apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  annotations:
    #external-dns.alpha.kubernetes.io/hostname: www.multi-region-domain.com
    loxilb.io/usepodnetwork : "yes"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: iperf-app
  ports:
    - port: 5001
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-daemonset
  labels:
    app: iperf-app
spec:
  selector:
    matchLabels:
      app: iperf-app
  template:
    metadata:
      labels:
        app: iperf-app
    spec:
      nodeSelector:
        node: wlznode02
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: iperf
        image: eyes852/ubuntu-iperf-test:0.5
        command: [ "iperf", "-s"]
        ports:
        - containerPort: 5001
