apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1
  annotations:
    #external-dns.alpha.kubernetes.io/hostname: www.multi-region-domain.com
    loxilb.io/usepodnetwork : "yes"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: nginx-test
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      nodeSelector:
        node: wlznode02
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nginx-test
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
